## NumPy

- массивы

In [1]:
print("Hello,Jupyter!")

Hello,Jupyter!


In [2]:
def func_1(arg_1, arg_2):
    print(arg_1 + arg_2)

func_1(10, 20)

30


In [3]:
# вывод без print
a = 10

a + 3
a + 4

14

In [4]:
# вывод с print

print(a + 2)
print(a + 5)

12
15


In [5]:
!pip3 install numpy

In [6]:
import numpy as np

In [7]:
# создание массивов

my_list = [4,2,1,5,7]
my_list


[4, 2, 1, 5, 7]

In [8]:
# создание 1-мерного массива (вектор)
np.array(my_list)

array([4, 2, 1, 5, 7])

In [9]:
# создание 2-мерного массива
my_list = [[10,20,30],[40,50,60]]
np.array(my_list)

array([[10, 20, 30],
       [40, 50, 60]])

In [10]:
# создание 1-мерного массива из нулей
z = np.zeros(5)
z

array([0., 0., 0., 0., 0.])

In [11]:
# массив из целочисленных значений
z.astype("int")

array([0, 0, 0, 0, 0])

In [12]:
# создание 2-мерного массива из нулей
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
# создание 2-мерного массива из единиц
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
# 1-мерный массив со значениями в линейной последовательности
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [16]:
# Из 1-мерного массива можно создать 2-мерный
# форма 2-мерного массива должна соответствовать длине исходного 1-мерного массива
arr = np.arange(10)
arr.reshape((2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [17]:
arr.reshape((5,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [18]:
arr.reshape((3,3))

ValueError: cannot reshape array of size 10 into shape (3,3)

In [19]:
# 1-мерный массив формой 5
# со случайными значениями из равномерного распределения
# в диапазоне от 0 до 1
np.random.random(5)

array([0.12986934, 0.98558262, 0.53820845, 0.92006843, 0.96958315])

In [20]:
# 2-мерный массив формой 3*5
np.random.random((3,5))

array([[0.44713261, 0.98187405, 0.83290405, 0.7451053 , 0.32668873],
       [0.73974601, 0.85714304, 0.02747772, 0.89918092, 0.92421982],
       [0.47712805, 0.26676477, 0.46258737, 0.55754876, 0.86855075]])