# NumPy

* Массивы

In [7]:
print("Hello, Jupyter!")

Hello, Jupyter!


In [6]:
def func_1(arg_1, arg_2):
    print(arg_1 + arg_2)

func_1(10, 20)

30


In [8]:
# вывод без print
a = 10

a + 3
a + 4

14

In [9]:
# вывод с print

print(a + 2)
print(a + 5)

12
15


In [8]:
!pip3 install numpy

In [1]:
import numpy as np

In [7]:
# создание массивов

my_list = [4,2,1,5,7]
my_list


[4, 2, 1, 5, 7]

In [8]:
# создание 1-мерного массива (вектор)
np.array(my_list)

array([4, 2, 1, 5, 7])

In [9]:
# создание 2-мерного массива
my_list = [[10,20,30],[40,50,60]]
np.array(my_list)

array([[10, 20, 30],
       [40, 50, 60]])

In [10]:
# создание 1-мерного массива из нулей
z = np.zeros(5)
z

array([0., 0., 0., 0., 0.])

In [11]:
# массив из целочисленных значений
z.astype("int")

array([0, 0, 0, 0, 0])

In [14]:
# создание 2-мерного массива из нулей
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
# создание 2-мерного массива из единиц
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
# 1-мерный массив со значениями в линейной последовательности
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [20]:
# Из 1-мерного массива можно создать 2-мерный
# форма 2-мерного массива должна соответствовать длине исходного 1-мерного массива
arr = np.arange(10)
arr.reshape((2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [21]:
arr.reshape((5,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [22]:
arr.reshape((3,3))

ValueError: cannot reshape array of size 10 into shape (3,3)

In [23]:
# 1-мерный массив формой 5
# со случайными значениями из равномерного распределения
# в диапазоне от 0 до 1
np.random.random(5)

array([0.11069797, 0.90813028, 0.75598084, 0.57217671, 0.8950142 ])

In [26]:
# 2-мерный массив формой 3*5
np.random.random((3,5))

array([[0.50387779, 0.03945562, 0.86657807, 0.87742559, 0.10630171],
       [0.88677561, 0.27221961, 0.92265783, 0.12733855, 0.57651883],
       [0.91178216, 0.10246673, 0.79868213, 0.65637494, 0.87996295]])