In [2]:
!pip install pandas

In [5]:
import numpy as np

In [10]:
# генерация массива со случайными целочисленными значениями
# одно случайное значение из диапазона от 0 до 10
# (скалярное значение)
np.random.randint(10)

3

In [14]:
np.random.randint(10, 20)

10

In [15]:
# 1-мерный массив со случайными целыми значениями
np.random.randint(10, size=5)

array([3, 2, 1, 3, 4])

In [13]:
np.random.randint(5, 10, size=5)

array([5, 8, 7, 8, 8])

In [16]:
# 2-мерный массив
np.random.randint(5, 10, size=(3,5))

array([[5, 9, 9, 7, 8],
       [8, 6, 8, 9, 5],
       [7, 7, 6, 7, 6]])

- атрибуты 

In [18]:
arr_1 = np.random.randint(10, size=(3,5))
arr_1

array([[4, 0, 6, 7, 9],
       [8, 0, 5, 3, 6],
       [3, 1, 2, 2, 0]])

In [19]:
# мерность массива (кол-во измерений/осей)
arr_1.ndim

2

In [20]:
# форма массива
arr_1.shape

(3, 5)

In [21]:
arr_1.shape[0]

3

In [22]:
# кол-во всех элементов массива
arr_1.size

15

In [23]:
# тип данных массива
arr_1.dtype

dtype('int64')

In [24]:
np.random.random(5).dtype

dtype('float64')

In [25]:
arr_1.astype("uint8")

array([[4, 0, 6, 7, 9],
       [8, 0, 5, 3, 6],
       [3, 1, 2, 2, 0]], dtype=uint8)

- индексация

In [28]:
arr_2 = np.random.randint(10, size=10)
arr_2

array([8, 8, 6, 5, 2, 2, 7, 0, 7, 6])

In [29]:
# прямая индексация
arr_2[0]

8

In [30]:
# обратная индексация
arr_2[-1]

6

In [31]:
# индексация 2-мерных массивов
arr_3 = np.random.randint(10, size=(3,4))
arr_3

array([[2, 8, 0, 9],
       [3, 1, 6, 1],
       [5, 4, 5, 3]])

In [32]:
# обычный синтаксис
arr_3[1][2]

6

In [33]:
# синтаксис numpy
arr_3[1, 2]

6

- срезы

In [34]:
# 1-мерный массив
arr_2[:5]

array([8, 8, 6, 5, 2])

In [36]:
arr_2[7:]

array([0, 7, 6])

In [37]:
arr_2[::-2]

array([6, 0, 2, 5, 8])

In [38]:
arr_2[-2:-6:-1]

array([7, 0, 7, 2])

In [39]:
# 2-мерный массив
arr_3[1:, :3]

array([[3, 1, 6],
       [5, 4, 5]])

In [40]:
arr_3[0, 1:]

array([8, 0, 9])

In [41]:
arr_3[:2, 1]

array([8, 1])

- представления (views) и копии (copies)

In [42]:
# срез списка создаёт копию
my_list = [1,2,3,4,5]
sub_list = my_list[2:]
sub_list

[3, 4, 5]

In [43]:
sub_list[0] = 100
sub_list

[100, 4, 5]

In [44]:
my_list

[1, 2, 3, 4, 5]

In [45]:
# срез массива создаёт представление исходного массива
my_arr = np.array([1,2,3,4,5])
sub_arr = my_arr[2:]
sub_arr

array([3, 4, 5])

In [46]:
sub_arr[0] = 10
sub_arr

array([10,  4,  5])

In [47]:
my_arr

array([ 1,  2, 10,  4,  5])

In [48]:
copy_arr = my_arr[2:].copy()
copy_arr

array([10,  4,  5])

In [49]:
copy_arr[0] = 1000
copy_arr

array([1000,    4,    5])

In [50]:
my_arr

array([ 1,  2, 10,  4,  5])

- изменение формы

In [51]:
# 1-мерный массив (вектор-строка)
arr_4 = np.arange(1, 10)
arr_4

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
arr_4.shape

(9,)

In [53]:
# вектор-строка
# технически это 2-мерный массив
arr_4.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [54]:
arr_5 = np.random.random((2,3))
arr_5

array([[0.38019676, 0.12959602, 0.41903312],
       [0.9720123 , 0.52394561, 0.35894729]])

In [55]:
arr_5.reshape((3,2))

array([[0.38019676, 0.12959602],
       [0.41903312, 0.9720123 ],
       [0.52394561, 0.35894729]])

In [56]:
arr_5.reshape((6,))

array([0.38019676, 0.12959602, 0.41903312, 0.9720123 , 0.52394561,
       0.35894729])

In [57]:
arr_5.reshape((6,1))

array([[0.38019676],
       [0.12959602],
       [0.41903312],
       [0.9720123 ],
       [0.52394561],
       [0.35894729]])

## Операции

- универсальные функции

In [58]:
a = np.arange(5)
b = np.arange(1,6)

print(a)
print(b)

[0 1 2 3 4]
[1 2 3 4 5]


In [59]:
# поэлемнтное сложение массивов
# "+" - алиас универсальной функции np.add()
a + b

array([1, 3, 5, 7, 9])

In [61]:
np.add(a, b)

array([1, 3, 5, 7, 9])

In [62]:
np.add(10, 20)

30

In [63]:
# поэлементное умноженте (произведение Адамара)
a * b

array([ 0,  2,  6, 12, 20])

In [66]:
a

array([0, 1, 2, 3, 4])

In [64]:
# матричное умножение
c = b.reshape((5,1))
c

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [65]:
np.dot(a, c)

array([40])

In [ ]:
# a[0] * c[0] + a[1] * c[1] + a[2] * c[2] + ...

In [85]:
# матричное умножение 2-мерных массивов
x = np.random.random((6,10))
y = np.random.randint(100, 999, size=(10,4))
np.dot(x, y)

array([[3148.68104359, 2908.68485579, 3672.08240853, 2895.74128633],
       [3097.20031321, 2677.13531491, 2896.11697896, 2776.71678072],
       [2122.06175536, 1821.94126431, 2600.18446014, 1935.55666545],
       [4057.86702683, 3152.44803127, 4231.53983469, 4061.43254491],
       [2786.13629587, 2886.31683672, 3414.81543178, 2916.47155965],
       [3254.94661245, 2613.22175868, 4016.71127116, 3257.17022503]])

In [84]:
z = np.random.randint(1000, size=30)
w = z.reshape((15, 2))
q = z.reshape((2, 15))
d = np.dot(q, w)
f = np.dot(w, q)