In [1]:
import numpy as np

- агрегирование
Агрегирование - вычисление неких сводных показателей.

In [2]:
arr_1 = np.random.random(10)
arr_1

array([0.24314414, 0.11581203, 0.24390438, 0.18172967, 0.76409321,
       0.52874915, 0.32838978, 0.26036677, 0.78774306, 0.01856909])

In [3]:
# сумма
# 1d-array
np.sum(arr_1)

3.472501285198164

In [4]:
# 2d-array
np.sum(arr_1.reshape((2,5)))

3.472501285198164

In [23]:
np.sum(arr_1.reshape((2,5)), axis=0)

array([0.7718933 , 0.44420181, 0.50427115, 0.96947274, 0.78266229])

In [5]:
# минимум
np.min(arr_1)

0.01856908544979219

In [6]:
# максимум
np.max(arr_1)

0.7877430648763226

In [7]:
# среднее арифметическое
np.mean(arr_1)

0.3472501285198164

- сравнение

In [8]:
arr_2 = np.arange(7)
arr_2

array([0, 1, 2, 3, 4, 5, 6])

In [9]:
arr_2 != 2

array([ True,  True, False,  True,  True,  True,  True])

In [10]:
arr_2 == 2

array([False, False,  True, False, False, False, False])

In [11]:
arr_2 > 3

array([False, False, False, False,  True,  True,  True])

In [12]:
np.arange(10).reshape((5,2)) >= 4

array([[False, False],
       [False, False],
       [ True,  True],
       [ True,  True],
       [ True,  True]])

In [13]:
# общее сравнение
# имеются ли в массиве значения, отвечающие условию
condition = arr_2 > 4
np.any(condition)

True

In [14]:
# все ли значения отвечают условию
np.all(arr_2 < 2)

False

In [15]:
arr_3 = np.arange(10).reshape((5,2))
arr_3

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [20]:
np.any(arr_3 > 7, axis=0)

array([ True,  True])

In [21]:
np.any(arr_3 > 7, axis=1)

array([False, False, False, False,  True])

In [22]:
np.all(arr_3 < 5, axis=0)

array([False, False])

- маскирование

In [24]:
arr_4 = np.random.randint(10, size=5)
arr_4

array([4, 8, 1, 8, 3])

In [25]:
# маска - массив сбулевыми значениями
c = arr_4 < 6
c

array([ True, False,  True, False,  True])

In [26]:
arr_4[c]

array([4, 1, 3])

In [32]:
# Побитовые операторы & = and, | = or
arr_4[(arr_4 > 5) & (arr_4 < 8)]

array([], dtype=int64)

In [33]:
arr_4[arr_4 != 8]

array([4, 1, 3])

- прихотливая индексация (fancy indieces)

In [34]:
arr_5 = np.arange(10, 20)
arr_5

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [36]:
# с помощью списка индексов
arr_5[[3,0,5,7]]

array([13, 10, 15, 17])

In [37]:
# с помощью массива индексов
arr_5[np.array([3,0,5,7])]

array([13, 10, 15, 17])

In [39]:
# с помощью прихотливой индексации можно менять форму результирующего массива
fi = np.array(
    [[3,0,1],
     [1,1,5]]
)
arr_5[fi]

array([[13, 10, 11],
       [11, 11, 15]])